/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ijnikkkk_encryptUtils */

#ifndef _Included_com_example_ijnikkkk_encryptUtils
#define _Included_com_example_ijnikkkk_encryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ijnikkkk_encryptUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ijnikkkk_encryptUtils_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_ijnikkkk_encryptUtils
 * Method:    sign
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ijnikkkk_encryptUtils_sign
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
